version: '3'
services:
  node:
    image: aaeventsapi-dev:v1
    build:
      context: .
      dockerfile: ./Dockerfile.prod
    env_file: ./.env
    container_name: aaeventsapi
    tty: true
    stdin_open: true
    volumes:
      - ./:/var/www/app
      - /var/www/app/node_modules
    working_dir: /var/www/app
    restart: always
    command: npm start
    expose:
      - 4005
    network_mode: webproxy
networks:
  default:
    external:
      name: webproxy
