version: '3'
services:
  node:
    image: superalgos/clone-executor:1.0.41
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: clone-executor
    tty: true
    stdin_open: true
    command: node Run.js
    restart: always
